#!/bin/bash

echo "本脚本为升级debian trixie的懒人脚本"
echo "作者:佚名"

# 询问用户是否继续
echo "是否继续执行操作？(y/n)"
read -r answer

# 将用户输入转换为小写，以便处理大小写不一致的情况
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')

# 根据用户的回答决定是否执行操作
if [ "$answer" = "y" ]; then
    echo "正在修改镜像源..."
else
    echo "正在退出脚本..."
    exit 0
fi

{
    echo "# Generated by distrobuilder"
    echo "##deb http://deb.debian.org/debian trixie main"
    echo "##deb http://deb.debian.org/debian trixie-updates main"
    echo "##deb http://deb.debian.org/debian-security/ trixie-security main"
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ trixie main contrib non-free"
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ trixie-updates main contrib non-free"
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ trixie-backports main contrib non-free"
    echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian-security/ trixie-security main contrib non-free"
    echo "# deb http://mirrors.tuna.tsinghua.edu.cn/debian/ sid main contrib non-free"
} > /etc/apt/sources.list

echo "修改成功."
echo ""
echo "正在更新源..."
sudo apt update -y
echo "更新成功."
echo ""
echo "正在更新软件包..."
sudo apt upgrade -y
sudo apt full-upgrade -y
sudo apt autoremove -y
sudo apt autoclean -y
echo "更新成功."
echo ""
echo "正在显示当前系统版本"
lsb_release -a
echo ""
# 询问用户是否继续
echo "是否重启？(y/n)"
read -r answer1

# 将用户输入转换为小写，以便处理大小写不一致的情况
answer1=$(echo "$answer1" | tr '[:upper:]' '[:lower:]')

# 根据用户的回答决定是否执行操作
if [ "$answer1" = "y" ]; then
    echo "将在三秒后执行重启命令..."
    sleep 3
    sudo reboot
else
    echo "用户选择不重启，正在退出..."
    exit 0
fi


