name: Trigger Workflow
on:
  workflow_dispatch:

jobs:
  trigger_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: 触发子工作流
        run: |
          #!/bin/bash
          total_jobs=140
          for ((i=1; i<=total_jobs; i++)); do
            echo "正在触发作业 $i"
            # 使用自定义的机密Token
            curl -X POST \
              -H "Authorization: token ${{ secrets.TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -d '{"ref":"main","inputs":{"job-index":"'$i'"}}' \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/job-workflow.yml/dispatches
            # 等待6小时再触发下一个作业
            sleep 21540
          done
